// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"focus-single/internal/dao/internal"
)

// internalWfMainFlowDao is internal type for wrapping internal DAO implements.
type internalWfMainFlowDao = *internal.WfMainFlowDao

// wfMainFlowDao is the data access object for table wf_main_flow.
// You can define custom methods on it to extend its functionality as you wish.
type wfMainFlowDao struct {
	internalWfMainFlowDao
}

var (
	// WfMainFlow is globally public accessible object for table wf_main_flow operations.
	WfMainFlow = wfMainFlowDao{
		internal.NewWfMainFlowDao(),
	}
)

// Fill with you ideas below.
